baseURL = "https://xxx.pages.dev/"
locale = "zh-cn"
title = "池州老洪的博客"
theme = "bearblog"
hasCJKLanguage = true

[params]
  author = "池州老洪"
  description = "个人文字随笔记录"
  darkModeAuto = true
  hideMadeWith = true