baseURL = "https://hongshunli-spec.github.io/blog/"
theme = "PaperMod"
# relativeURLs = true  #注释掉，不要写在这里
languageCode = "zh‑CN"

[params]
title = "池州老洪的博客"
description = "技术笔记博客"
author = "池州老洪"

[params.appearance]
theme = "auto"
darkMode = true