name: Deploy Hexo Blog

on:
  push:
    branches:
      - main # 当检测到 main 分支有代码推送时触发

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '26' # 这里的 Node 版本保持与你本地一致

      - name: Install dependencies
        run: |
          npm ci

      - name: Build static files
        run: |
          npx hexo generate

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: public # 将 hexo 生成的 public 文件夹推送到 gh-pages 分支
          branch: gh-pages 

